services:
  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    container_name: coddog-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-coddog}
      POSTGRES_USER: ${POSTGRES_USER:-coddog}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "5432:5432"
    networks:
      - coddog-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-coddog} -d ${POSTGRES_DB:-coddog}"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB

  # Coddog API
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: coddog-api
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-coddog}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-coddog}
      - SERVER_ADDRESS=0.0.0.0:3000
      - DB_WINDOW_SIZE=${DB_WINDOW_SIZE:-8}
      - RUST_LOG=${RUST_LOG:-info}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - coddog-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: coddog-frontend
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - coddog-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

volumes:
  postgres_data:
    driver: local

networks:
  coddog-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16