/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SymbolIndexRouteImport } from './routes/symbol/index'
import { Route as SymbolSymbolSlugRouteImport } from './routes/symbol/$symbolSlug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SymbolIndexRoute = SymbolIndexRouteImport.update({
  id: '/symbol/',
  path: '/symbol/',
  getParentRoute: () => rootRouteImport,
} as any)
const SymbolSymbolSlugRoute = SymbolSymbolSlugRouteImport.update({
  id: '/symbol/$symbolSlug',
  path: '/symbol/$symbolSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/symbol/$symbolSlug': typeof SymbolSymbolSlugRoute
  '/symbol': typeof SymbolIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/symbol/$symbolSlug': typeof SymbolSymbolSlugRoute
  '/symbol': typeof SymbolIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/symbol/$symbolSlug': typeof SymbolSymbolSlugRoute
  '/symbol/': typeof SymbolIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/symbol/$symbolSlug' | '/symbol'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/symbol/$symbolSlug' | '/symbol'
  id: '__root__' | '/' | '/admin' | '/symbol/$symbolSlug' | '/symbol/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  SymbolSymbolSlugRoute: typeof SymbolSymbolSlugRoute
  SymbolIndexRoute: typeof SymbolIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symbol/': {
      id: '/symbol/'
      path: '/symbol'
      fullPath: '/symbol'
      preLoaderRoute: typeof SymbolIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symbol/$symbolSlug': {
      id: '/symbol/$symbolSlug'
      path: '/symbol/$symbolSlug'
      fullPath: '/symbol/$symbolSlug'
      preLoaderRoute: typeof SymbolSymbolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  SymbolSymbolSlugRoute: SymbolSymbolSlugRoute,
  SymbolIndexRoute: SymbolIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
