/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as MatchIndexImport } from './routes/match/index'
import { Route as MatchSymbolIdImport } from './routes/match/$symbolId'

// Create/Update Routes

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MatchIndexRoute = MatchIndexImport.update({
  id: '/match/',
  path: '/match/',
  getParentRoute: () => rootRoute,
} as any)

const MatchSymbolIdRoute = MatchSymbolIdImport.update({
  id: '/match/$symbolId',
  path: '/match/$symbolId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/match/$symbolId': {
      id: '/match/$symbolId'
      path: '/match/$symbolId'
      fullPath: '/match/$symbolId'
      preLoaderRoute: typeof MatchSymbolIdImport
      parentRoute: typeof rootRoute
    }
    '/match/': {
      id: '/match/'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/match/$symbolId': typeof MatchSymbolIdRoute
  '/match': typeof MatchIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/match/$symbolId': typeof MatchSymbolIdRoute
  '/match': typeof MatchIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/match/$symbolId': typeof MatchSymbolIdRoute
  '/match/': typeof MatchIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/match/$symbolId' | '/match'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/match/$symbolId' | '/match'
  id: '__root__' | '/' | '/admin' | '/match/$symbolId' | '/match/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  MatchSymbolIdRoute: typeof MatchSymbolIdRoute
  MatchIndexRoute: typeof MatchIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  MatchSymbolIdRoute: MatchSymbolIdRoute,
  MatchIndexRoute: MatchIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/match/$symbolId",
        "/match/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx"
    },
    "/match/$symbolId": {
      "filePath": "match/$symbolId.tsx"
    },
    "/match/": {
      "filePath": "match/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
