[package]
name = "coddog-api"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"
description = """
An api for finding matching sequences of code among binaries
"""

[dependencies]
anyhow = "1.0"
axum = "0.8.4"
tokio = { version = "1.45.1", features = ["full"] }
serde_json = "1.0"
dotenvy = "0.15.7"
sqlx = { version = "0.8", features = ["macros", "migrate", "runtime-tokio", "postgres"] }
tower-http = { version = "0.6.6", features = ["cors"] }
coddog-db = { path = "../db" }
coddog-core = { path = "../core" }